global class GLOBALSTATICFLAG{
    
    global static boolean BYPASSOPPORTUNTIYAFTERUPDATETRIGGER = false;
    global static boolean BYPASSOPPORTUNTIYBEFOREUPDATETRIGGER = false;
    global static boolean BYPASSUNITAFTERUPDATETRIGGER = false;
    global static boolean BYPASSUNITBEFOREUPDATETRIGGER = false;
    global static boolean BYPASSFLOORAFTERUPDATETRIGGER = false;
    global static boolean BYPASSFLOORBEFOREUPDATETRIGGER = false;
    global static boolean BYPASSBUILDINGAFTERUPDATETRIGGER = false;
    global static boolean BYPASSBUIDLINGBEFOREUPDATETRIGGER = false;
    global static boolean BYPASSCALLINGLISTAFTERUPDATETRIGGER = false;
    global static boolean BYPASSINVOICEAFTERUPDATETRIGGER = false;
    global static boolean BYPASSINVOICEAFTERINSERTTRIGGER = false;
    
    
}