/****************************************************************************************************************************
* @Name         NKLResponseTest
* @Author       Kaustubh Abhyankar
* @Date         05-May-2022
* @Description  Test Class for NKLResponse
****************************************************************************************************************************/

@isTest
public class NKLResponseTest {
    @isTest
    public static void ResposeTest() {
        NKLResponse nkl = new NKLResponse();
        nkl.data = null;
        nkl.message = null;
        nkl.success = null;
    }
}